### ISSUE TITLE
Tailored to navigation

### ISSUE THREAD

**Issue by llxClover** [AnthonyFavier/human_sim_ws#1]
Could you tell me how to implement the experiments which you mentioned in _Tailored to navigation_?
How to launch some _*.launch_ files?

**Comment by AnthonyFavier** [comment]
Hi ! The experiments shown in the _Tailored to navigation_ section are running in the MORSE simulator and correspond to different scenarios of the default map (laas_adream). Those scenarios can be selected through the Boss component. In the experiments, the human avatar is running the InHuS System with the enhanced navigation (inhus_cohan_nav) and the robot is running the actual CoHAN planner that you can find here (https://github.com/sphanit/CoHAN_Navigation, https://github.com/sphanit/cohan_planner_multi). 
_*.launch_ files are related to ROS. Then I suggest you to get familiar with ROS and to follow the installation instructions. Then focus on the _Enhanced navigation example_ section to run the examples. Currently working on Ubuntu 18.04 with ROS Melodic.
Let me know if you have further issues.
