### ISSUE TITLE
Failed to reproduce human-robot interactive motion

### ISSUE THREAD

**Issue by JiangxinkeTao** [AnthonyFavier/human_sim_ws#2]
Dear author, hello, the work you did is very beautiful, but when I reproduce your work, I always make errors and cannot achieve the effect as shown in the picture. I followed the operation in your README document, but RVIZ did not respond accordingly. 
**I sincerely hope you can give me an answer, thank you very sincerely!** 
![image](https://github.com/AnthonyFavier/InHuS_Social_Navigation/assets/42513042/26ff2688-76dc-4fba-8d5c-989f914d0cc2)

**my step**
roslaunch inhus_navigation stage_simulator.launch
roslaunch inhus_navigation inhus_cohan_nav.launch
roslaunch inhus_navigation morse_simulator.launch

Sincerely hope to get your help

**Comment by AnthonyFavier** [comment]
Hi,
Thank you for your interest in my work ! I'm sorry that you're facing issues running the system..
Unfortunately, I won't have much time to help you in the following weeks. 
Nevertheless, from the screenshot you share it seems that you have a robot localization problem (the white square on Rviz should be a PR2 robot not located in the wall). So check the "fake" localization processes that should be started by the robot launch files.
Also, be careful about the commands. You should either run the three following commands to run the simulator with the Stage simulator:
```
roslaunch inhus_navigation stage_simulator.launch
roslaunch inhus_navigation inhus_nav.launch
roslaunch smb all.launch
```
Or the two following commands to run the MORSE simulator:
```
roslaunch inhus_navigation morse_simulator.launch
roslaunch inhus_navigation inhus_cohan_nav.launch
```
But never  `stage_simulator.launch` and `morse_simulator.launch` at the same time as your 2nd picture suggests. There will be conflicts.

I hope you will be able to run the system and reproduce the navigation scenarios. I will try to provide further help when possible if you still face issues.

Best

**Comment by JiangxinkeTao** [comment]
Thank you, dear author, your suggestion is useful, now I can reproduce the code, my sincere thanks and good luck to you. I will close the issue.
